name: test-application-node
on:
  pull_request:
    branches:
      - develop

jobs:
  application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm run test
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}